resolver: lts-7.19
packages:
  - .
  - location:
      git: https://github.com/thitp/hsmecab.git
      commit: a663c6e12e591fa6125dee06546613585fe2d6ce
    extra-dep: true
extra-lib-dirs:
  - /usr/local/lib
extra-include-dirs:
  - /usr/local/include
